env:
  global:
    - CC_TEST_REPORTER_ID=99c5e5ff3403f7330e464781b3852d419561959fbb3636dded7a1f679c99be37

language: node_js
node_js:
  - "10"
  - "8"
  - "6"
dist: trusty
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_success:
  - yarn run jest --coverage
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
